name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install packages
        run: |
          sudo apt update
          sudo apt install -y python3-pip git zip unzip openjdk-17-jdk

      - name: Install tools
        run: |
          pip install buildozer cython

      # ✅ ADD THIS HERE (inside steps, not top)
      - name: Accept Android SDK Licenses
        run: |
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses || true

      - name: Build APK
        run: |
          buildozer init
          sed -i 's/title = My Application/title = My First App/' buildozer.spec
          sed -i 's/package.name = myapp/package.name = myfirstapp/' buildozer.spec
          buildozer android debug